const SPY_ELEMENT_LABELS = {
  901: "Métal",
  902: "Cristal",
  903: "Deutérium",
  911: "Énergie",
  202: "Petit transporteur",
  203: "Grand transporteur",
  204: "Chasseur léger",
  205: "Chasseur lourd",
  206: "Croiseur",
  207: "Vaisseau de bataille",
  208: "Vaisseau de colonisation",
  209: "Recycleur",
  210: "Sonde d'espionnage",
  211: "Bombardier",
  212: "Satellite solaire",
  213: "Destructeur",
  214: "Étoile de la mort",
  215: "Traqueur",
  217: "Transporteur ultime",
  220: "Collectionneur",
  401: "Lanceur de missiles",
  402: "Canon laser léger",
  403: "Canon laser puissant",
  404: "Canon de Gauss",
  405: "Artillerie à Ions",
  406: "Lanceur de Plasma",
  407: "Petit bouclier",
  408: "Grand bouclier",
  409: "Dôme de protection",
  410: "Canon à gravitons",
  411: "Plateforme orbitale",
  502: "Missiles d'interception",
  503: "Missiles interplanétaires",
  1: "Mine de métal",
  2: "Mine de cristal",
  3: "Synthétiseur de deutérium",
  4: "Centrale solaire",
  6: "Université",
  12: "Centrale de fusion",
  14: "Usine de robots",
  15: "Usine de nanites",
  21: "Chantier spatial",
  22: "Hangar de métal",
  23: "Hangar de cristal",
  24: "Réservoir de deutérium",
  31: "Laboratoire de recherche",
  33: "Terraformeur",
  34: "Dépôt d'alliance",
  41: "Base lunaire",
  42: "Phalange de capteurs",
  43: "Porte de saut",
  44: "Silo de missiles",
  99: "Rampe de production de masse",
  106: "Technologie d'espionnage",
  108: "Technologie ordinateur",
  109: "Technologie armes",
  110: "Technologie bouclier",
  111: "Technologie blindage",
  113: "Technologie énergie",
  114: "Technologie hyperespace",
  115: "Réacteur à combustion",
  117: "Réacteur à impulsion",
  118: "Propulsion hyperespace",
  120: "Technologie laser",
  121: "Technologie ion",
  122: "Technologie plasma",
  123: "Réseau de recherche intergalactique",
  124: "Astrophysique",
  131: "Optimisation production métal",
  132: "Optimisation production cristal",
  133: "Optimisation production deutérium",
  199: "Technologie graviton",
};

const SPY_DETAIL_SECTIONS = [
  { key: "900", title: "Ressources", mode: "amount", total: (report) => report.lootFormatted },
  { key: "200", title: "Flotte", mode: "count", total: (report) => report.fleetFormatted },
  { key: "400", title: "Défense", mode: "count", total: (report) => report.defenseFormatted },
];
